Make Zeek 5.1 compatible
Currently this plugin fails with Zeek 5.1 due to the following error:

    src/HTTP2.cc:146:13: error: ‘ProtocolConfirmation’ was not declared in this scope; did you mean ‘LN_protocolInformation’?
      146 |             ProtocolConfirmation(); // Notify system that this is HTTP2.
          |             ^~~~~~~~~~~~~~~~~~~~
          |             LN_protocolInformation
    src/HTTP2.cc:158:17: error: ‘ProtocolViolation’ was not declared in this scope
      158 |                 ProtocolViolation("Unable to parse http 2 frame from data stream, fatal error");

With Zeek 5.1 ProtocolConfirmation() and ProtocolViolation() have been
removed. Since Zeek 4.2 there's AnalyzerConfirmation() and
AnalyzerViolation() available.